name: floors
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: any
  json_annotation: any

  shelf: any
  shelf_router: any

  common:
    path: ../common

  database:
    path: ../database

  users:
    path: ../users

  media:
    path: ../media

dev_dependencies:
  lints: ^5.0.0
  build_runner: any
  json_serializable: any
  freezed: any
