import 'package:devices/devices.dart';

String getNameByType({
  required DeviceType type,
}) {
  return switch (type) {
    DeviceType.light => 'Лампочка',
    DeviceType.mediaDeviceTV => 'Телевизор',
    DeviceType.cookingKettle => 'Чайник',
    DeviceType.vacuumCleaner => 'Робот пылесос',
    DeviceType.thermostatAc => 'Кондиционер',
    DeviceType.sensorClimate => 'Датчик климата',
    DeviceType.sensorMotion => 'Датчик движения',
    DeviceType.sensorOpen => 'Датчик открытия',
    DeviceType.switch_ => 'Выключатель',
    DeviceType.openableCurtain => 'Шторы',
    DeviceType.sensorSmoke => 'Датчик дыма',
    DeviceType.sensorGas => 'Датчик газа',
    DeviceType.sensorWaterLeak => 'Датчик протечки',
    DeviceType.sensorVibration => 'Датчик вибрации',
    DeviceType.other => 'Другое',
    DeviceType.camera => 'Камера',
    DeviceType.lightCeiling => 'Потолочная лампа',
    DeviceType.lightStrip => 'Светодиодная лента',
    DeviceType.mediaDevice => 'Медиа-устройство',
    DeviceType.mediaDeviceReceiver => 'Медиаплеер',
    DeviceType.mediaDeviceTVBox => 'ТВ приставка',
    DeviceType.cooking => 'Кухонное устройство',
    DeviceType.cookingCoffeeMaker => 'Кофеварка',
    DeviceType.cookingMulticooker => 'Мультиварка',
    DeviceType.dishwasher => 'Посудомоечная машина',
    DeviceType.iron => 'Утюг',
    DeviceType.washingMachine => 'Стиральная машина',
    DeviceType.petDrinkingFountain => 'Поилка для питомца',
    DeviceType.petFeeder => 'Кормушка для питомца',
    DeviceType.humidifier => 'Увлажнитель',
    DeviceType.purifier => 'Очиститель воздуха',
    DeviceType.thermostat => 'Термостат',
    DeviceType.ventilation => 'Вентиляция',
    DeviceType.ventilationFan => 'Вентилятор',
    DeviceType.lightLamp => 'Настольная лампа',
    DeviceType.socket => 'Розетка',
    DeviceType.switchRelay => 'Релейный выключатель',
    DeviceType.openable => 'Открывающееся устройство',
    DeviceType.openableValve => 'Клапан',
    DeviceType.sensor => 'Датчик',
    DeviceType.sensorButton => 'Кнопочный датчик',
    DeviceType.sensorIllumination => 'Датчик освещенности',
    DeviceType.smartMeter => 'Счетчик',
    DeviceType.smartMeterColdWater => 'Счетчик холодной воды',
    DeviceType.smartMeterElectricity => 'Электросчетчик',
    DeviceType.smartMeterGas => 'Газовый счетчик',
    DeviceType.smartMeterHeat => 'Тепловой счетчик',
    DeviceType.smartMeterHotWater => 'Счетчик горячей воды',
    DeviceType.microphone => 'Микрофон',
    DeviceType.doorWithLock => 'Дверь с замком',
    DeviceType.smartHub => 'Смарт-хаб',
    DeviceType.controlBoxHub => 'Щит управления (хаб)',
    DeviceType.cameraHub => 'Камера-хаб',
  };
}
