name: auth_token
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: any
  json_annotation: any

  shelf: any
  shelf_router: any

  dart_jsonwebtoken: ^2.0.0

  common:
    path: ../common

  refresh_token:
    path: ../refresh_token

  users:
    path: ../users

  devices:
    path: ../devices

dev_dependencies:
  lints: ^5.0.0
  build_runner: any
  json_serializable: any
  freezed: any
