// Mocks generated by Mockito 5.4.6 from annotations
// in auth/test/widgets_test/application/screens/sign_in_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i4;

import 'package:auth/src/application/controllers/sign_in_validation_controller.dart'
    as _i3;
import 'package:auth_token/src/domain/domain.dart' as _i5;
import 'package:common/common.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValidationField_0<T> extends _i1.SmartFake
    implements _i2.ValidationField<T> {
  _FakeValidationField_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SignInValidationController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInValidationController extends _i1.Mock
    implements _i3.SignInValidationController {
  @override
  List<_i2.ValidationField<dynamic>> get validationsfields =>
      (super.noSuchMethod(
        Invocation.getter(#validationsfields),
        returnValue: <_i2.ValidationField<dynamic>>[],
        returnValueForMissingStub: <_i2.ValidationField<dynamic>>[],
      ) as List<_i2.ValidationField<dynamic>>);

  @override
  bool get hasVisibleError => (super.noSuchMethod(
        Invocation.getter(#hasVisibleError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasErrors => (super.noSuchMethod(
        Invocation.getter(#hasErrors),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.ValidationField<String> get nameField => (super.noSuchMethod(
        Invocation.getter(#nameField),
        returnValue: _FakeValidationField_0<String>(
          this,
          Invocation.getter(#nameField),
        ),
        returnValueForMissingStub: _FakeValidationField_0<String>(
          this,
          Invocation.getter(#nameField),
        ),
      ) as _i2.ValidationField<String>);

  @override
  _i2.ValidationField<String> get passwordField => (super.noSuchMethod(
        Invocation.getter(#passwordField),
        returnValue: _FakeValidationField_0<String>(
          this,
          Invocation.getter(#passwordField),
        ),
        returnValueForMissingStub: _FakeValidationField_0<String>(
          this,
          Invocation.getter(#passwordField),
        ),
      ) as _i2.ValidationField<String>);

  @override
  String? getFieldVisibleError(_i2.ValidationField<dynamic>? field) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFieldVisibleError,
          [field],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  bool addFieldWithVisibleError(_i2.ValidationField<dynamic>? field) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFieldWithVisibleError,
          [field],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool validateField<T>(
    _i2.ValidationField<T>? field,
    T? newValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateField,
          [
            field,
            newValue,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool validateAll() => (super.noSuchMethod(
        Invocation.method(
          #validateAll,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ISignInController].
///
/// See the documentation for Mockito's code generation for more information.
class MockISignInController extends _i1.Mock implements _i5.ISignInController {
  @override
  _i5.SignInState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i6.dummyValue<_i5.SignInState>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _i6.dummyValue<_i5.SignInState>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i5.SignInState);

  @override
  void signIn({required _i5.SignInInputEntity? data}) => super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {#data: data},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [IAuthTokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthTokenRepository extends _i1.Mock
    implements _i5.IAuthTokenRepository {
  @override
  _i7.Stream<_i5.AuthTokenEntity?> get tokenChanged => (super.noSuchMethod(
        Invocation.getter(#tokenChanged),
        returnValue: _i7.Stream<_i5.AuthTokenEntity?>.empty(),
        returnValueForMissingStub: _i7.Stream<_i5.AuthTokenEntity?>.empty(),
      ) as _i7.Stream<_i5.AuthTokenEntity?>);

  @override
  _i7.Future<_i5.AuthTokenEntity?> fetchToken() => (super.noSuchMethod(
        Invocation.method(
          #fetchToken,
          [],
        ),
        returnValue: _i7.Future<_i5.AuthTokenEntity?>.value(),
        returnValueForMissingStub: _i7.Future<_i5.AuthTokenEntity?>.value(),
      ) as _i7.Future<_i5.AuthTokenEntity?>);

  @override
  _i7.Future<void> revokeToken() => (super.noSuchMethod(
        Invocation.method(
          #revokeToken,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.AuthTokenEntity> refreshToken(
          {required _i5.RefreshTokenInputEntity? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [],
          {#data: data},
        ),
        returnValue: _i7.Future<_i5.AuthTokenEntity>.value(
            _i6.dummyValue<_i5.AuthTokenEntity>(
          this,
          Invocation.method(
            #refreshToken,
            [],
            {#data: data},
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i5.AuthTokenEntity>.value(
            _i6.dummyValue<_i5.AuthTokenEntity>(
          this,
          Invocation.method(
            #refreshToken,
            [],
            {#data: data},
          ),
        )),
      ) as _i7.Future<_i5.AuthTokenEntity>);

  @override
  _i7.Future<_i5.AuthTokenEntity> signIn(
          {required _i5.SignInInputEntity? data}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
          {#data: data},
        ),
        returnValue: _i7.Future<_i5.AuthTokenEntity>.value(
            _i6.dummyValue<_i5.AuthTokenEntity>(
          this,
          Invocation.method(
            #signIn,
            [],
            {#data: data},
          ),
        )),
        returnValueForMissingStub: _i7.Future<_i5.AuthTokenEntity>.value(
            _i6.dummyValue<_i5.AuthTokenEntity>(
          this,
          Invocation.method(
            #signIn,
            [],
            {#data: data},
          ),
        )),
      ) as _i7.Future<_i5.AuthTokenEntity>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i5.AuthTokenEntity?> updateToken({_i5.AuthTokenEntity? token}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateToken,
          [],
          {#token: token},
        ),
        returnValue: _i7.Future<_i5.AuthTokenEntity?>.value(),
        returnValueForMissingStub: _i7.Future<_i5.AuthTokenEntity?>.value(),
      ) as _i7.Future<_i5.AuthTokenEntity?>);
}
