name: scenarios_service
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  inout_scenarios:
    path: packages/inout_scenarios

  device_scenarios:
    path: packages/device_scenarios

  dio: ^5.8.0+1

  devices: any
  events: any
  common: any

dependency_overrides:
  devices:
    git:
      url: https://github.com/Zotov-Dev/smart_home-shared_packages.git
      path: devices
      ref: v1.3.0

  common:
    git:
      url: https://github.com/Zotov-Dev/smart_home-shared_packages.git
      path: common
      ref: v1.3.0

  events:
    git:
      url: https://github.com/Zotov-Dev/smart_home-shared_packages.git
      path: events
      ref: v1.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
