import 'package:common/common.dart';

part 'isapi_event_entity.freezed.dart';

@Freezed(copyWith: true, equal: true)
sealed class IsapiEventEntity with _$IsapiEventEntity {
  const IsapiEventEntity._();

  const factory IsapiEventEntity({
    required DateTime dateTime,
    required IsapiEventType type,
    required String? name,
  }) = _IsapiEventEntity;
}

enum IsapiEventType {
  // Major 0x1 - Alarm events
  alarmIn, // 0x1
  alarmOut, // 0x2
  motionDetectStart, // 0x3
  motionDetectStop, // 0x4
  hideAlarmStart, // 0x5
  hideAlarmStop, // 0x6
  vcaAlarmStart, // 0x7
  vcaAlarmStop, // 0x8
  netAlarmStart, // 0xb
  netAlarmStop, // 0xc
  alarmInRevert, // 0xd
  alarmInShortCircuit, // 0x400
  alarmInBrokenCircuit, // 0x401
  alarmInException, // 0x402
  alarmInResume, // 0x403
  hostDesmantleAlarm, // 0x404
  hostDesmantleResume, // 0x405
  cardReaderDesmantleAlarm, // 0x406
  cardReaderDesmantleResume, // 0x407
  caseSensorAlarm, // 0x408
  caseSensorResume, // 0x409
  stressAlarm, // 0x40a
  offlineEventNearlyFull, // 0x40b
  cardMaxAuthenticateFail, // 0x40c
  sdCardFull, // 0x40d
  linkageCapturePic, // 0x40e
  securityModuleDesmantleAlarm, // 0x40f
  securityModuleDesmantleResume, // 0x410
  posStartAlarm, // 0x411
  posEndAlarm, // 0x412
  faceImageQualityLow, // 0x413
  fingerPrintQualityLow, // 0x414
  fireImportShortCircuit, // 0x415
  fireImportBrokenCircuit, // 0x416
  fireImportResume, // 0x417
  fireButtonTrigger, // 0x418
  fireButtonResume, // 0x419
  maintenanceButtonTrigger, // 0x41a
  maintenanceButtonResume, // 0x41b
  emergencyButtonTrigger, // 0x41c
  emergencyButtonResume, // 0x41d
  distractControllerAlarm, // 0x41e
  distractControllerResume, // 0x41f
  channelControllerDesmantleAlarm, // 0x422
  channelControllerDesmantleResume, // 0x423
  channelControllerFireImportAlarm, // 0x424
  channelControllerFireImportResume, // 0x425
  printerOutOfPaper, // 0x440
  pswOpenDoorFailedOverlimit, // 0x441
  legalEventNearlyFull, // 0x442
  transactionRecordNearlyFull, // 0x444
  distractControllerFireImportShortCircuit, // 0x95e
  distractControllerFireImportResumeAlt, // 0x95f

  // Major 0x2 - Exception events
  viLost, // 0x21
  illegalAccess, // 0x22
  hdFull, // 0x23
  hdError, // 0x24
  dcdLost, // 0x25
  ipConflict, // 0x26
  netBroken, // 0x27
  recError, // 0x28
  ipcNoLink, // 0x29
  viException, // 0x2a
  ipcIpConflict, // 0x2b
  fanAbnormal, // 0x31
  fanResume, // 0x32
  subsystemAbnormalReboot, // 0x33
  matrixStartBuzzer, // 0x34
  netAbnormal, // 0x35
  memAbnormal, // 0x36
  fileAbnormal, // 0x37
  rs485DeviceAbnormal, // 0x3a
  rs485DeviceRevert, // 0x3b
  devPowerOn, // 0x400
  devPowerOff, // 0x401
  watchDogReset, // 0x402
  lowBattery, // 0x403
  batteryResume, // 0x404
  acOff, // 0x405
  acResume, // 0x406
  netResume, // 0x407
  flashAbnormal, // 0x408
  cardReaderOffline, // 0x409
  cardReaderResume, // 0x40a
  indicatorLightOff, // 0x40b
  indicatorLightResume, // 0x40c
  channelControllerOff, // 0x40d
  channelControllerResume, // 0x40e
  securityModuleOff, // 0x40f
  securityModuleResume, // 0x410
  batteryElectricLow, // 0x411
  batteryElectricResume, // 0x412
  localControlNetBroken, // 0x413
  localControlNetResume, // 0x414
  masterRs485LoopnodeBroken, // 0x415
  masterRs485LoopnodeResume, // 0x416
  localControlOffline, // 0x417
  localControlResume, // 0x418
  localDownsideRs485LoopnodeBroken, // 0x419
  localDownsideRs485LoopnodeResume, // 0x41a
  distractControllerOnline, // 0x41b
  distractControllerOffline, // 0x41c
  idCardReaderNotConnect, // 0x41d
  idCardReaderResume, // 0x41e
  fingerPrintModuleNotConnect, // 0x41f
  fingerPrintModuleResume, // 0x420
  cameraNotConnect, // 0x421
  cameraResume, // 0x422
  comNotConnect, // 0x423
  comResume, // 0x424
  deviceNotAuthorize, // 0x425
  peopleAndIdCardDeviceOnline, // 0x426
  peopleAndIdCardDeviceOffline, // 0x427
  localLoginLock, // 0x428
  localLoginUnlock, // 0x429
  submarinebackCommBreak, // 0x42a
  submarinebackCommResume, // 0x42b
  motorSensorException, // 0x42c
  canBusException, // 0x42d
  canBusResume, // 0x42e
  gateTemperatureOverrun, // 0x42f
  irEmitterException, // 0x430
  irEmitterResume, // 0x431
  lampBoardCommException, // 0x432
  lampBoardCommResume, // 0x433
  irAdaptorCommException, // 0x434
  irAdaptorCommResume, // 0x435
  printerOnline, // 0x436
  printerOffline, // 0x437
  fourGModuleOnline, // 0x438
  fourGModuleOffline, // 0x439
  dspStartFailed, // 0x43a
  smartRegulationNotAllowed, // 0x43b
  auxiliaryBoardOffline, // 0x43c
  auxiliaryBoardResume, // 0x43d
  idcardSecurityModuleException, // 0x43e
  idcardSecurityModuleResume, // 0x43f
  fpPeripheralException, // 0x440
  fpPeripheralResume, // 0x441
  smartPlateOffline, // 0x444
  smartPlateOnline, // 0x445
  refundLocked, // 0x446
  coderOnline, // 0x447
  coderOffline, // 0x448
  keyboardOffline, // 0x449
  keyboardOnline, // 0x44a
  fiveGModuleOnline, // 0x44b
  fiveGModuleOffline, // 0x44c
  extendModuleOnline, // 0x44d
  extendModuleOffline, // 0x44e
  interlockServerDisconnected, // 0x44f
  interlockServerConnected, // 0x450
  qrcodeReaderOffline, // 0x451
  qrcodeReaderOnline, // 0x452
  optionalBoardOffline, // 0x455
  optionalBoardResume, // 0x456
  usbOnline, // 0x953
  usbOffline, // 0x954
  localControlBackupException, // 0x955
  socialSecurityCardReaderOnline, // 0x956
  socialSecurityCardReaderOffline, // 0x957
  channelInfraredDetectorException, // 0x958
  channelInfraredDetectorWorkingException, // 0x959
  channelInfraredDetectorDetectException, // 0x95a
  channelInfraredDetectorNoTargetCalibrateException, // 0x95b
  channelInfraredDetectorTargetDistanceErrorCalibrateException, // 0x95c
  channelInfraredNoChannelWidth, // 0x95d

  // Major 0x3 - Operation events
  startDvr, // 0x41
  stopDvr, // 0x42
  stopAbnormal, // 0x43
  rebootDvr, // 0x44
  localLogin, // 0x50
  localLogout, // 0x51
  localModifyTime, // 0x59
  localUpgrade, // 0x5a
  localCfgfileOutput, // 0x5d
  localCfgfileInput, // 0x5e
  localModifyPassword, // 0x6d
  remoteLogin, // 0x70
  remoteLogout, // 0x71
  remoteGetParam, // 0x76
  remoteCfgParam, // 0x77
  remoteGetStatus, // 0x78
  remoteArm, // 0x79
  remoteDisarm, // 0x7a
  remoteReboot, // 0x7b
  remoteUpgrade, // 0x7e
  remoteCfgfileOutput, // 0x86
  remoteCfgfileInput, // 0x87
  remoteAlarmoutOpenMan, // 0xd6
  remoteAlarmoutCloseMan, // 0xd7
  remoteLoginLock, // 0x137
  remoteLoginUnlock, // 0x138
  remoteOpenDoor, // 0x400
  remoteCloseDoor, // 0x401
  remoteAlwaysOpen, // 0x402
  remoteAlwaysClose, // 0x403
  remoteCheckTime, // 0x404
  ntpCheckTime, // 0x405
  remoteClearCard, // 0x406
  remoteRestoreCfg, // 0x407
  alarminArm, // 0x408
  alarminDisarm, // 0x409
  localRestoreCfg, // 0x40a
  remoteCapturePic, // 0x40b
  modNetReportCfg, // 0x40c
  modGprsReportParam, // 0x40d
  modReportGroupParam, // 0x40e
  unlockPasswordOpenDoor, // 0x40f
  autoRenumber, // 0x410
  autoComplementNumber, // 0x411
  normalCfgfileInput, // 0x412
  normalCfgfileOutput, // 0x413
  cardRightInput, // 0x414
  cardRightOutput, // 0x415
  localUsbUpgrade, // 0x416
  remoteVisitorCallLadder, // 0x417
  remoteHouseholdCallLadder, // 0x418
  remoteActualGuard, // 0x419
  remoteActualUnguard, // 0x41a
  remoteControlNotCodeOperFailed, // 0x41b
  remoteControlCloseDoor, // 0x41c
  remoteControlOpenDoor, // 0x41d
  remoteControlAlwaysOpenDoor, // 0x41e
  m1CardEncryptVerifyOpen, // 0x41f
  m1CardEncryptVerifyClose, // 0x420
  nfcFunctionOpen, // 0x421
  nfcFunctionClose, // 0x422
  offlineDataOutput, // 0x423
  localLoginUnlockOp, // 0x429
  createSshLink, // 0x42d
  closeSshLink, // 0x42e
  localImportUserinfo, // 0x42f
  localExportUserinfo, // 0x430
  createCertificate, // 0x431
  uploadCertificate, // 0x432
  deleteCertificate, // 0x433
  comsumeArm, // 0x434
  comsumeDisarm, // 0x435
  orcodeKeyModify, // 0x436
  distractControllerReboot, // 0x97f
  distractControllerResumeCfg, // 0x980
  alarmhostLocalSetDeviceActive, // 0xf0
  alarmhostRemoteSetDeviceActive, // 0xf1
  localResetLoginPassword, // 0x2600
  remoteModifyPassword, // 0x2601

  // Major 0x5 - Access control events
  legalCardPass, // 0x01
  cardAndPswPass, // 0x02
  cardAndPswFail, // 0x03
  cardAndPswTimeout, // 0x04
  cardAndPswOverTime, // 0x05
  cardNoRight, // 0x06
  cardInvalidPeriod, // 0x07
  cardOutOfDate, // 0x08
  invalidCard, // 0x09
  antiSneakFail, // 0x0a
  interlockDoorNotClose, // 0x0b
  notBelongMultiGroup, // 0x0c
  invalidMultiVerifyPeriod, // 0x0d
  multiVerifySuperRightFail, // 0x0e
  multiVerifyRemoteRightFail, // 0x0f
  multiVerifySuccess, // 0x10
  leaderCardOpenBegin, // 0x11
  leaderCardOpenEnd, // 0x12
  alwaysOpenBegin, // 0x13
  alwaysOpenEnd, // 0x14
  lockOpen, // 0x15
  lockClose, // 0x16
  doorButtonPress, // 0x17
  doorButtonRelease, // 0x18
  doorOpenNormal, // 0x19
  doorCloseNormal, // 0x1a
  doorOpenAbnormal, // 0x1b
  doorOpenTimeout, // 0x1c
  alarmoutOn, // 0x1d
  alarmoutOff, // 0x1e
  alwaysCloseBegin, // 0x1f
  alwaysCloseEnd, // 0x20
  multiVerifyNeedRemoteOpen, // 0x21
  multiVerifySuperpasswdVerifySuccess, // 0x22
  multiVerifyRepeatVerify, // 0x23
  multiVerifyTimeout, // 0x24
  doorbellRinging, // 0x25
  fingerprintComparePass, // 0x26
  fingerprintCompareFail, // 0x27
  cardFingerprintVerifyPass, // 0x28
  cardFingerprintVerifyFail, // 0x29
  cardFingerprintVerifyTimeout, // 0x2a
  cardFingerprintPasswdVerifyPass, // 0x2b
  cardFingerprintPasswdVerifyFail, // 0x2c
  cardFingerprintPasswdVerifyTimeout, // 0x2d
  fingerprintPasswdVerifyPass, // 0x2e
  fingerprintPasswdVerifyFail, // 0x2f
  fingerprintPasswdVerifyTimeout, // 0x30
  fingerprintInexistence, // 0x31
  cardPlatformVerify, // 0x32
  callCenter, // 0x33
  fireRelayTurnOnDoorAlwaysOpen, // 0x34
  fireRelayRecoverDoorRecoverNormal, // 0x35
  faceAndFpVerifyPass, // 0x36
  faceAndFpVerifyFail, // 0x37
  faceAndFpVerifyTimeout, // 0x38
  faceAndPwVerifyPass, // 0x39
  faceAndPwVerifyFail, // 0x3a
  faceAndPwVerifyTimeout, // 0x3b
  faceAndCardVerifyPass, // 0x3c
  faceAndCardVerifyFail, // 0x3d
  faceAndCardVerifyTimeout, // 0x3e
  faceAndPwAndFpVerifyPass, // 0x3f
  faceAndPwAndFpVerifyFail, // 0x40
  faceAndPwAndFpVerifyTimeout, // 0x41
  faceCardAndFpVerifyPass, // 0x42
  faceCardAndFpVerifyFail, // 0x43
  faceCardAndFpVerifyTimeout, // 0x44
  employeenoAndFpVerifyPass, // 0x45
  employeenoAndFpVerifyFail, // 0x46
  employeenoAndFpVerifyTimeout, // 0x47
  employeenoAndFpAndPwVerifyPass, // 0x48
  employeenoAndFpAndPwVerifyFail, // 0x49
  employeenoAndFpAndPwVerifyTimeout, // 0x4a
  faceVerifyPass, // 0x4b
  faceVerifyFail, // 0x4c
  employeenoAndFaceVerifyPass, // 0x4d
  employeenoAndFaceVerifyFail, // 0x4e
  employeenoAndFaceVerifyTimeout, // 0x4f
  faceRecognizeFail, // 0x50
  firstcardAuthorizeBegin, // 0x51
  firstcardAuthorizeEnd, // 0x52
  doorlockInputShortCircuit, // 0x53
  doorlockInputBrokenCircuit, // 0x54
  doorlockInputException, // 0x55
  doorcontactInputShortCircuit, // 0x56
  doorcontactInputBrokenCircuit, // 0x57
  doorcontactInputException, // 0x58
  openbuttonInputShortCircuit, // 0x59
  openbuttonInputBrokenCircuit, // 0x5a
  openbuttonInputException, // 0x5b
  doorlockOpenException, // 0x5c
  doorlockOpenTimeout, // 0x5d
  firstcardOpenWithoutAuthorize, // 0x5e
  callLadderRelayBreak, // 0x5f
  callLadderRelayClose, // 0x60
  autoKeyRelayBreak, // 0x61
  autoKeyRelayClose, // 0x62
  keyControlRelayBreak, // 0x63
  keyControlRelayClose, // 0x64
  employeenoAndPwPass, // 0x65
  employeenoAndPwFail, // 0x66
  employeenoAndPwTimeout, // 0x67
  humanDetectFail, // 0x68
  peopleAndIdCardComparePass, // 0x69
  peopleAndIdCardCompareFail, // 0x70
  certificateBlackList, // 0x71
  legalMessage, // 0x72
  illegalMessage, // 0x73
  doorOpenOrDormantFail, // 0x75
  authPlanDormantFail, // 0x76
  cardEncryptVerifyFail, // 0x77
  submarinebackReplyFail, // 0x78
  doorOpenOrDormantOpenFail, // 0x82
  doorOpenOrDormantLinkageOpenFail, // 0x84
  trailing, // 0x85
  reverseAccess, // 0x86
  forceAccess, // 0x87
  climbingOverGate, // 0x88
  passingTimeout, // 0x89
  intrusionAlarm, // 0x8a
  freeGatePassNotAuth, // 0x8b
  dropArmBlock, // 0x8c
  dropArmBlockResume, // 0x8d
  localFaceModelingFail, // 0x8e
  stayEvent, // 0x8f
  certificateAllowlistPass, // 0x90
  certificateAllowlistFall, // 0x91
  pswErrorOverTimes, // 0x94
  idCardCollection, // 0x95
  pswVerifyFail, // 0x96
  passwordMismatch, // 0x97
  employeeNoNotExist, // 0x98
  combinedVerifyPass, // 0x99
  combinedVerifyTimeout, // 0x9a
  verifyModeMismatch, // 0x9b
  orcodeVerifyPass, // 0x9c
  orcodeVerifyFail, // 0x9d
  householderAuthorizePass, // 0x9e
  bluetoothVerifyPass, // 0x9f
  bluetoothVerifyFail, // 0xa0
  passportVerifyFail, // 0xa1
  informalMifareCardVerifyFail, // 0xa2
  cpuCardEncryptVerifyFail, // 0xa3
  nfcDisableVerifyFail, // 0xa4
  loraModuleOnline, // 0xa5
  loraModuleOffline, // 0xa6
  mqttStatus, // 0xa7
  emCardRecognizeNotEnabled, // 0xa8
  m1CardRecognizeNotEnabled, // 0xa9
  cpuCardRecognizeNotEnabled, // 0xaa
  idCardRecognizeNotEnabled, // 0xab
  cardSetSecretKeyFail, // 0xac
  localUpgradeFail, // 0xad
  remoteUpgradeFail, // 0xae
  remoteExtendModuleUpgradeSucc, // 0xaf
  remoteExtendModuleUpgradeFail, // 0xb0
  remoteFingerPrintModuleUpgradeSucc, // 0xb1
  remoteFingerPrintModuleUpgradeFail, // 0xb2
  dynamiccodeVerifyPass, // 0xb3
  dynamiccodeVerifyFail, // 0xb4
  passwdVerifyPass, // 0xb5
  comsumeTimeout, // 0xb6
  refundTimeout, // 0xb7
  comsumeAmountOverlimit, // 0xb8
  comsumeTimesOverlimit, // 0xb9
  userComsumeEnsureTimeout, // 0xba
  desfireCardEncryptVerifyFail, // 0xbc
  desfireCardRecognizeNotEnabled, // 0xbd
  irisVerifyPass, // 0xbe
  irisVerifyFail, // 0xbf
  irisBioassayFail, // 0xc0
  fullStaff, // 0xc1
  meetingNoSignin, // 0xc4
  meetingSignin, // 0xc5
  meetingLate, // 0xc6
  interlockServerFailedResponse, // 0xc9
  fingerprintDisenabeldVerifyFail, // 0xca
  faceDisenabeldVerifyFail, // 0xcb
  monitorOpenDoor, // 0xcc
  readerFactoryReset, // 0xcd
  readerIdConflict, // 0xce
  felicaCardRecognizeNotEnabled, // 0xcf
  propertyExceptionVerifyFail, // 0xd0
  authenticationTimesReached, // 0xd4
  orcodeKeyVerifyFail, // 0xd9
  personPassThrough, // 0xda
  peopleAndSocialSecurityCardComparePass, // 0xdb
  peopleAndSocialSecurityCardCompareFail, // 0xdc
  distractControllerUpgradeSucc, // 0xe0
  distractControllerUpgradeFail, // 0xe1
  remoteImportUserData, // 0x544
  remoteExportUserData, // 0x545
  vpAntiSpoofingFail, // 0x700
  vpVerifyFail, // 0x701
  channelSecurityAreaOccupy, // 0x800
  channelAntiPinchAreaOccupy, // 0x801
  channelMotorBrakeWorking, // 0x802
  channelSelfCheckFail, // 0x803
  channelMotorSelfLearningFail, // 0x804
  channelAlarmAreaNotOpenDoor, // 0x805
  channelMotorDriveBoardException, // 0x806
  channelMotorEncodeException, // 0x807
  channelMotorOvercurrent, // 0x808
  channelMotorOvervoltage, // 0x809
  channelMotorUndervoltage, // 0x80a
  channelMotorException, // 0x80b
  channelPermissionAuthBlocked, // 0x80c
  rmVerifyPass, // 0x80d
  rmVerifyFail, // 0x80e
  doorLockDelay, // 0x813
  allowNouseDoor, // 0x814
  cardAuthFail, // 0x815

  // Legacy compatibility
  faceAuth,
  doorOpened,
  doorClosed,
  lockUnlocked,
  lockLocked,
  lockUnlockedFromApp,

  unknown,
}
