import 'package:devices/devices.dart';

abstract final class DeviceTypeMapper {
  static String toModel({required DeviceType from}) {
    return switch (from) {
      DeviceType.sensor => 'sensor',
      DeviceType.sensorButton => 'sensor_button',
      DeviceType.sensorClimate => 'sensor_climate',
      DeviceType.sensorGas => 'sensor_gas',
      DeviceType.sensorIllumination => 'sensor_illumination',
      DeviceType.sensorMotion => 'sensor_motion',
      DeviceType.sensorOpen => 'sensor_open',
      DeviceType.sensorSmoke => 'sensor_smoke',
      DeviceType.sensorVibration => 'sensor_vibration',
      DeviceType.sensorWaterLeak => 'sensor_water_leak',
      DeviceType.smartMeter => 'smart_meter',
      DeviceType.smartMeterColdWater => 'smart_meter_cold_water',
      DeviceType.smartMeterElectricity => 'smart_meter_electricity',
      DeviceType.smartMeterGas => 'smart_meter_gas',
      DeviceType.smartMeterHeat => 'smart_meter_heat',
      DeviceType.smartMeterHotWater => 'smart_meter_hot_water',
      DeviceType.camera => 'camera',
      DeviceType.mediaDevice => 'media_device',
      DeviceType.mediaDeviceReceiver => 'media_device_receiver',
      DeviceType.mediaDeviceTV => 'media_device_tv',
      DeviceType.mediaDeviceTVBox => 'media_device_tv_box',
      DeviceType.cooking => 'cooking',
      DeviceType.cookingCoffeeMaker => 'cooking_coffee_maker',
      DeviceType.cookingKettle => 'cooking_kettle',
      DeviceType.cookingMulticooker => 'cooking_multicooker',
      DeviceType.dishwasher => 'dishwasher',
      DeviceType.iron => 'iron',
      DeviceType.vacuumCleaner => 'vacuum_cleaner',
      DeviceType.washingMachine => 'washing_machine',
      DeviceType.petDrinkingFountain => 'pet_drinking_fountain',
      DeviceType.petFeeder => 'pet_feeder',
      DeviceType.humidifier => 'humidifier',
      DeviceType.purifier => 'purifier',
      DeviceType.ventilation => 'ventilation',
      DeviceType.ventilationFan => 'ventilation_fan',
      DeviceType.socket => 'socket',
      DeviceType.switch_ => 'switch',
      DeviceType.switchRelay => 'switch_relay',
      DeviceType.openable => 'openable',
      DeviceType.openableCurtain => 'openable_curtain',
      DeviceType.openableValve => 'openable_valve',
      DeviceType.light => 'light',
      DeviceType.lightLamp => 'light_lamp',
      DeviceType.lightCeiling => 'light_ceiling',
      DeviceType.lightStrip => 'light_strip',
      DeviceType.thermostat => 'thermostat',
      DeviceType.thermostatAc => 'thermostat_ac',
      DeviceType.microphone => 'microphone',
      DeviceType.doorWithLock => 'door_with_lock',
      DeviceType.smartHub => 'smart_hub',
      DeviceType.controlBoxHub => 'control_box_hub',
      DeviceType.cameraHub => 'camera_hub',
      DeviceType.other => 'other',
    };
  }

  static DeviceType toEntity({required String from}) {
    return switch (from) {
      'sensor' => DeviceType.sensor,
      'sensor_button' => DeviceType.sensorButton,
      'sensor_climate' => DeviceType.sensorClimate,
      'sensor_gas' => DeviceType.sensorGas,
      'sensor_illumination' => DeviceType.sensorIllumination,
      'sensor_motion' => DeviceType.sensorMotion,
      'sensor_open' => DeviceType.sensorOpen,
      'sensor_smoke' => DeviceType.sensorSmoke,
      'sensor_vibration' => DeviceType.sensorVibration,
      'sensor_water_leak' => DeviceType.sensorWaterLeak,
      'smart_meter' => DeviceType.smartMeter,
      'smart_meter_cold_water' => DeviceType.smartMeterColdWater,
      'smart_meter_electricity' => DeviceType.smartMeterElectricity,
      'smart_meter_gas' => DeviceType.smartMeterGas,
      'smart_meter_heat' => DeviceType.smartMeterHeat,
      'smart_meter_hot_water' => DeviceType.smartMeterHotWater,
      'camera' => DeviceType.camera,
      'media_device' => DeviceType.mediaDevice,
      'media_device_receiver' => DeviceType.mediaDeviceReceiver,
      'media_device_tv' => DeviceType.mediaDeviceTV,
      'media_device_tv_box' => DeviceType.mediaDeviceTVBox,
      'cooking' => DeviceType.cooking,
      'cooking_coffee_maker' => DeviceType.cookingCoffeeMaker,
      'cooking_kettle' => DeviceType.cookingKettle,
      'cooking_multicooker' => DeviceType.cookingMulticooker,
      'dishwasher' => DeviceType.dishwasher,
      'iron' => DeviceType.iron,
      'vacuum_cleaner' => DeviceType.vacuumCleaner,
      'washing_machine' => DeviceType.washingMachine,
      'pet_drinking_fountain' => DeviceType.petDrinkingFountain,
      'pet_feeder' => DeviceType.petFeeder,
      'humidifier' => DeviceType.humidifier,
      'purifier' => DeviceType.purifier,
      'ventilation' => DeviceType.ventilation,
      'ventilation_fan' => DeviceType.ventilationFan,
      'socket' => DeviceType.socket,
      'switch' => DeviceType.switch_,
      'switch_relay' => DeviceType.switchRelay,
      'openable' => DeviceType.openable,
      'openable_curtain' => DeviceType.openableCurtain,
      'openable_valve' => DeviceType.openableValve,
      'light' => DeviceType.light,
      'light_lamp' => DeviceType.lightLamp,
      'light_ceiling' => DeviceType.lightCeiling,
      'light_strip' => DeviceType.lightStrip,
      'thermostat' => DeviceType.thermostat,
      'thermostat_ac' => DeviceType.thermostatAc,
      'microphone' => DeviceType.microphone,
      'door_with_lock' => DeviceType.doorWithLock,
      'smart_hub' => DeviceType.smartHub,
      'control_box_hub' => DeviceType.controlBoxHub,
      'camera_hub' => DeviceType.cameraHub,
      _ => DeviceType.other,
    };
  }
}
