name: auth_token
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  dio: any
  retrofit: any
  freezed_annotation: any
  json_annotation: any

  common:
    path: ../common

  flutter_secure_storage: ^9.2.4

  jwt_decoder: ^2.0.1
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  freezed: any
  auto_route_generator: any
