name: common
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: any
  json_annotation: any
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  dio: ^5.3.2
  collection: ^1.19.1

dev_dependencies:
  build_runner: any
  json_serializable: any
  freezed: any
