name: sync_service
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0

  devices: any
  events: any
  common: any

  shelf_proxy: ^1.0.4
  web_socket_channel: ^3.0.2
  shelf_web_socket: ^2.0.1
  bluez: ^0.8.3
  dbus: ^0.7.11
  rpi_gpio: ^0.10.0
  retrofit: "4.5.0" # Temporary pinned version due to issues with latest versions

dependency_overrides:
  devices:
    git:
      url: https://github.com/Zotov-Dev/smart_home-shared_packages.git
      path: devices
      ref: v1.6.2

  common:
    git:
      url: https://github.com/Zotov-Dev/smart_home-shared_packages.git
      path: common
      ref: v1.6.2

  events:
    git:
      url: https://github.com/Zotov-Dev/smart_home-shared_packages.git
      path: events
      ref: v1.6.2

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0
